from django.utils.translation import gettext_lazy as _

LISTA_INTREBARI = [
    {"id": 1, "text": _("Eu am succes acolo unde alții nu au, dar nu pentru că eu fac planuri mai bune, ci pentru că eu insist, în timp ce alții se descurajează și renunță.")},
    {"id": 2, "text": _("Firea mea calmă mă ajută să stau liniștit în fața tulburărilor și stresului.")},
    {"id": 3, "text": _("Atunci când îmi fac planuri, cred că am capacitatea să identific destul de exact piedicile și pericolele.")},
    {"id": 4, "text": _("Mă deranjează entuziasmul unor oameni și cred că uneori îi «înțep».")},
    {"id": 5, "text": _("De obicei, aștept ca alții să intre în discuție cu mine, să mă abordeze.")},
    {"id": 6, "text": _("Aptitudinile mele de conducător sunt rezultatul stăruinței și efortului. Ele nu sunt un dar natural.")},
    {"id": 7, "text": _("Îmi este greu să vorbesc cu alții, dar îmi este ușor să-i evaluez și să-i analizez.")},
    {"id": 8, "text": _("Adesea întârzii la întâlniri și constat că uit hotărârile care s-au luat.")},
    {"id": 9, "text": _("Nu sunt o persoană cu foarte mulți prieteni, dar sunt profund atașată de prietenii pe care îi am.")},
    {"id": 10, "text": _("Mă influențează oamenii și situațiile în care mă aflu. De exemplu: dacă ceilalți sunt harnici, sunt și eu; dacă ei sunt leneși, lenevesc și eu.")},
    {"id": 11, "text": _("Întotdeauna știu ce trebuie să fac, și dacă trebuie să fac ceva, nu sunt mulțumit până nu-mi termin munca.")},
    {"id": 12, "text": _("De regulă, prefer activitățile de unul singur (de exemplu lectura), în locul activităților care implică și pe alții.")},
    {"id": 13, "text": _("Revin de nenumărate ori asupra unei decizii pe care am luat-o, întrebându-mă dacă am luat decizia cea bună.")},
    {"id": 14, "text": _("Câteodată ajut pe cineva fără tragere de inimă, pentru că știu că pot să fac un plan mai bun și mai ușor de realizat.")},
    {"id": 15, "text": _("Adesea mă gândesc la persoanele care m-au insultat. Nu le uit.")},
    {"id": 16, "text": _("Îmi place să mă bucur de viață și se pare că atitudinea mea îi molipsește pe cei din jur.")},
    {"id": 17, "text": _("Mă cercetez adesea și retrăiesc evenimentele din trecut.")},
    {"id": 18, "text": _("Am o minte ascuțită și sunt capabil să fac planuri foarte bune, chiar și pe termen lung.")},
    {"id": 19, "text": _("Poate aș fi mai sociabil dacă nu mi-ar fi teamă că oamenii mă vor respinge.")},
    {"id": 20, "text": _("Îmi place să fiu acolo unde se întâmplă ceva.")},
    {"id": 21, "text": _("Sunt mâhnit când ceilalți mă ignoră sau mă evită.")},
    {"id": 22, "text": _("Unii îmi spun că sunt născut să fiu conducător, datorită tendinței mele de a lua comanda.")},
    {"id": 23, "text": _("Știu unde am de gând să ajung și, de obicei, îmi impun să ajung acolo.")},
    {"id": 24, "text": _("În general, nu-i uit pe cei care m-au jignit.")},
    {"id": 25, "text": _("Mă emoționez repede. Tot ce se întâmplă în jur mă afectează.")},
    {"id": 26, "text": _("Trebuie să se întâmple ceva ieșit din comun ca să mă emoționeze și să mă afecteze.")},
    {"id": 27, "text": _("Răspunsurile mele emoționale sunt echilibrate.")},
    {"id": 28, "text": _("Când văd că doi oameni râd, mă întreb dacă nu cumva râd de mine.")},
    {"id": 29, "text": _("Am o stare sufletească destul de constantă, fără prea multe oscilații.")},
    {"id": 30, "text": _("Prietenii mei m-ar descrie ca pe un om relaxat, cu un temperament echilibrat.")},
    {"id": 31, "text": _("Ar trebui să mă cunosc mai bine; am tendința de a-mi subestima capacitățile.")},
    {"id": 32, "text": _("Dacă trebuie să fac ceva, o fac, oricât ar fi de neplăcut.")},
    {"id": 33, "text": _("Mă gândesc adesea la visurile, speranțele și năzuințele mele.")},
    {"id": 34, "text": _("Pot să mă împac cu neîmplinirile mele, fără să ajung deprimat sau mânios.")},
    {"id": 35, "text": _("Îmi fac prieteni noi cu atâta ușurință, încât tind să-i uit pe cei vechi.")},
    {"id": 36, "text": _("Îmi place să fac parte din diferite grupuri și să am preocupări variate.")},
    {"id": 37, "text": _("Sunt înclinat spre gânduri pesimiste și sumbre.")},
    {"id": 38, "text": _("Adesea mi-e greu să termin ceea ce am început.")},
    {"id": 39, "text": _("Între oameni, sunt spontan și vorbăreț.")},
    {"id": 40, "text": _("De obicei nu mă simt bine în grup.")},
    {"id": 41, "text": _("Îmi plac oamenii și tind să fiu mereu printre ei.")},
    {"id": 42, "text": _("Cred că n-ar trebui să fiu așa de capricios și sensibil.")},
    {"id": 43, "text": _("De obicei sunt defensiv, nu ofensiv.")},
    {"id": 44, "text": _("Câteodată mă gândesc să mă răzbun pentru răul care mi s-a făcut vreodată.")},
    {"id": 45, "text": _("Piedicile mă fac și mai hotărât.")},
    {"id": 46, "text": _("Am o viață sufletească profundă.")},
    {"id": 47, "text": _("Îmi place să-mi organizez planurile din timp.")},
    {"id": 48, "text": _("Sunt prietenos. Sunt plin de viață și-mi place să trăiesc.")},
    {"id": 49, "text": _("Se pare că, din fire, sunt un împăciuitor destul de bun.")},
    {"id": 50, "text": _("Prietenii mă consideră o persoană cu tact.")},
    {"id": 51, "text": _("Sunt destul de îngăduitor cu ceilalți.")},
    {"id": 52, "text": _("De obicei îmi organizez foarte bine lucrul.")},
    {"id": 53, "text": _("Când lucrurile nu merg cum trebuie, nu mă dau bătut, ci sunt mai hotărât să le duc până la capăt.")},
    {"id": 54, "text": _("Am darul să rezolv problemele.")},
    {"id": 55, "text": _("Sunt calm, liniștit și echilibrat.")},
    {"id": 56, "text": _("Am tendința să mă simt jignit foarte ușor.")},
    {"id": 57, "text": _("Mă consider o persoană sociabilă, bine dispusă.")},
    {"id": 58, "text": _("Am tendința să mă auto-compătimesc.")},
    {"id": 59, "text": _("Sunt o persoană destul de curajoasă în public.")},
    {"id": 60, "text": _("Unul dintre punctele mele tari este voința puternică.")},
    {"id": 61, "text": _("Mă simt foarte bine când particip la serbări.")},
    {"id": 62, "text": _("De obicei îmi este ușor să-mi fac noi prieteni.")},
    {"id": 63, "text": _("Stilul meu de viață este rapid, precipitat și activ.")},
    {"id": 64, "text": _("Trebuie să învăț să nu mă îngrijorez atât de mult.")},
    {"id": 65, "text": _("De obicei, acționez și vorbesc lent și calm.")},
    {"id": 66, "text": _("Am tendința să mă tot gândesc la aceleași lucruri.")},
    {"id": 67, "text": _("Sunt o persoană cu care ceilalți se înțeleg destul de ușor.")},
    {"id": 68, "text": _("De regulă, termin ce am început.")},
    {"id": 69, "text": _("Nu mi se întâmplă prea des să fiu întors pe dos.")},
    {"id": 70, "text": _("Rareori rămân în pană de cuvinte.")},
    {"id": 71, "text": _("De obicei, mă bucur din plin de viață.")},
    {"id": 72, "text": _("Prietenii mei ar spune că sunt extrovertit (deschis).")},
    {"id": 73, "text": _("Adesea sunt înclinat să mă analizez.")},
    {"id": 74, "text": _("Îndatoririle neterminate mă supără destul de mult.")},
    {"id": 75, "text": _("Nu-mi ies prea ușor din fire.")},
    {"id": 76, "text": _("De obicei, muncesc din greu și cu stăruință.")},
    {"id": 77, "text": _("Nu-mi plac persoanele care mi se împotrivesc.")},
    {"id": 78, "text": _("Rareori se întâmplă să mă mânii sau să mă las stăpânit de emoții.")},
    {"id": 79, "text": _("Îmi este greu să-mi fac noi prieteni.")},
    {"id": 80, "text": _("Poate că n-ar trebui să fiu așa de leneș.")}
]