# Generated by Django 6.0.2 on 2026-02-17 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RezultatTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scor_coleric', models.FloatField(default=0.0)),
                ('scor_sangvin', models.FloatField(default=0.0)),
                ('scor_flegmatic', models.FloatField(default=0.0)),
                ('scor_melancolic', models.FloatField(default=0.0)),
                ('data_completarii', models.DateTimeField(auto_now=True)),
                ('utilizator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
