# Generated by Django 6.0.2 on 2026-02-17 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezultattest',
            old_name='scor_coleric',
            new_name='procent_coleric',
        ),
        migrations.RenameField(
            model_name='rezultattest',
            old_name='scor_flegmatic',
            new_name='procent_flegmatic',
        ),
        migrations.RenameField(
            model_name='rezultattest',
            old_name='scor_melancolic',
            new_name='procent_melancolic',
        ),
        migrations.RenameField(
            model_name='rezultattest',
            old_name='scor_sangvin',
            new_name='procent_sangvin',
        ),
        migrations.AlterField(
            model_name='rezultattest',
            name='data_completarii',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rezultattest',
            name='utilizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
